/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/Navigation`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/EditProfile`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/Notification`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/StudentDashboard`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/StudentProfile`; params?: Router.UnknownInputParams; } | { pathname: `/StudentLogin`; params?: Router.UnknownInputParams; } | { pathname: `/StudentRegister`; params?: Router.UnknownInputParams; } | { pathname: `/Teacher/layout`; params?: Router.UnknownInputParams; } | { pathname: `/Teacher/TeacherNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/Teacher/TeacherAttendance`; params?: Router.UnknownInputParams; } | { pathname: `/Teacher/TeacherDashboard`; params?: Router.UnknownInputParams; } | { pathname: `/Teacher/TeacherNotifications`; params?: Router.UnknownInputParams; } | { pathname: `/TeacherLogin`; params?: Router.UnknownInputParams; } | { pathname: `/TeacherRegister`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/Navigation`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/EditProfile`; params?: Router.UnknownOutputParams; } | { pathname: `/navigation/Notification`; params?: Router.UnknownOutputParams; } | { pathname: `/navigation/StudentDashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/navigation/StudentProfile`; params?: Router.UnknownOutputParams; } | { pathname: `/StudentLogin`; params?: Router.UnknownOutputParams; } | { pathname: `/StudentRegister`; params?: Router.UnknownOutputParams; } | { pathname: `/Teacher/layout`; params?: Router.UnknownOutputParams; } | { pathname: `/Teacher/TeacherNavigator`; params?: Router.UnknownOutputParams; } | { pathname: `/Teacher/TeacherAttendance`; params?: Router.UnknownOutputParams; } | { pathname: `/Teacher/TeacherDashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/Teacher/TeacherNotifications`; params?: Router.UnknownOutputParams; } | { pathname: `/TeacherLogin`; params?: Router.UnknownOutputParams; } | { pathname: `/TeacherRegister`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/Navigation${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/EditProfile${`?${string}` | `#${string}` | ''}` | `/navigation/Notification${`?${string}` | `#${string}` | ''}` | `/navigation/StudentDashboard${`?${string}` | `#${string}` | ''}` | `/navigation/StudentProfile${`?${string}` | `#${string}` | ''}` | `/StudentLogin${`?${string}` | `#${string}` | ''}` | `/StudentRegister${`?${string}` | `#${string}` | ''}` | `/Teacher/layout${`?${string}` | `#${string}` | ''}` | `/Teacher/TeacherNavigator${`?${string}` | `#${string}` | ''}` | `/Teacher/TeacherAttendance${`?${string}` | `#${string}` | ''}` | `/Teacher/TeacherDashboard${`?${string}` | `#${string}` | ''}` | `/Teacher/TeacherNotifications${`?${string}` | `#${string}` | ''}` | `/TeacherLogin${`?${string}` | `#${string}` | ''}` | `/TeacherRegister${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/Navigation`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/EditProfile`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/Notification`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/StudentDashboard`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/StudentProfile`; params?: Router.UnknownInputParams; } | { pathname: `/StudentLogin`; params?: Router.UnknownInputParams; } | { pathname: `/StudentRegister`; params?: Router.UnknownInputParams; } | { pathname: `/Teacher/layout`; params?: Router.UnknownInputParams; } | { pathname: `/Teacher/TeacherNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/Teacher/TeacherAttendance`; params?: Router.UnknownInputParams; } | { pathname: `/Teacher/TeacherDashboard`; params?: Router.UnknownInputParams; } | { pathname: `/Teacher/TeacherNotifications`; params?: Router.UnknownInputParams; } | { pathname: `/TeacherLogin`; params?: Router.UnknownInputParams; } | { pathname: `/TeacherRegister`; params?: Router.UnknownInputParams; };
    }
  }
}
